#/vis/open OGLIQt 1200x600
/qsim/fSourceMode 1
/gun/particle e-

/qsim/xmin 0.0 cm
/qsim/xmax 0.0 cm
/qsim/ymin -0.5 cm
/qsim/ymax 0.5 cm

/qsim/z -11.0 cm

/qsim/thetamin 0.0 deg
/qsim/thetamax 0.0 deg

/qsim/fLGReflectivity 0.9
/qsim/fAllowCerenkov 1
/qsim/fAllowScintillation 1

#/gun/position 0.0 0.0 -11.0 cm
#/gun/direction 0 0 1

/qsim/emin 850 MeV
/qsim/emax 850 MeV


#/control/execute vis/vis.mac

/run/initialize 

/qsim/filename qsimout_0.0_degrees_0.0_x.root
/run/beamOn 100000
