
# Set run mode
#/qsim/fDetMode 1 
#/qsim/fStandMode 0 
/qsim/fSourceMode 1 

# Set detector properties
/qsim/fQuartzPolish 0.975 
/qsim/fDetAngle 0 deg
/qsim/fDetPosX 0 cm
/qsim/fDetPosY 0 cm

/qsim/emin 3.0 GeV  #1.063 GeV
/qsim/emax 8.0 GeV  #1.063 GeV
/qsim/xmin -0.15 m
/qsim/xmax 0.35 m
/qsim/ymin -0.25 m
/qsim/ymax 0.25 m
/qsim/thetamin -3.0 deg
/qsim/thetamax 3.0 deg
/qsim/z -0.52 m


# initialize
/run/initialize


/qsim/filename qsim_out.root
#/qsim/seed 50 

/gun/particle e- 


#
# Create a new empty scene
#
/vis/scene/create


#
# Declare that the world volume should be added to the scene
#
/vis/scene/add/volume
#
#
# Attach scene to scenehandler
#
/vis/sceneHandler/attach

# Add axis (has to be after /vis/scene/create )
#
/vis/scene/add/axes 0 0 0 100 cm


#
# Draw a picture that has just the detector (no trajectories or hits).
#
/vis/viewer/flush

#
# Declare that trajectories and hits should be added to the scene
#
/vis/scene/add/trajectories
/vis/scene/add/hits

#
# Set camera
#
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 35 15 deg
/vis/viewer/zoom 2.0

#
# Set surface
#
/vis/viewer/set/style surface

#/vis/viewer/addCutawayPlane 0.0 0.0 0.0 m 1.0 0.0 0.0
/vis/viewer/set/lightsMove with-camera
#
# Create style
#
/vis/modeling/trajectories/create/drawByParticleID MollerStyle
/vis/modeling/trajectories/MollerStyle/set e- red
/vis/modeling/trajectories/MollerStyle/set e+ blue
/vis/modeling/trajectories/MollerStyle/set gamma green
/vis/modeling/trajectories/MollerStyle/set neutron white
/vis/modeling/trajectories/MollerStyle/set opticalphoton yellow
/vis/modeling/trajectories/MollerStyle/set proton magenta
#
/vis/modeling/trajectories/select MollerStyle

#
# Event action
#
/vis/scene/endOfEventAction accumulate

#
# Run action
#
/vis/scene/endOfRunAction refresh

